---
apiVersion: v1
kind: Service
metadata:
  name: vault-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 8200
    targetPort: 8200
    nodePort: 30445
  selector:
    app.kubernetes.io/name: vault
    component: server
